### ISSUE TITLE
Noel c'est un ouf malade

### ISSUE THREAD

**Issue by kristofbc** [RignonNoel/ionic-tasklist#10]
Enough said

**Comment by RignonNoel** [comment]
Ah!! commence pas a me peter mes issues xD

**Comment by RignonNoel** [comment]
Va plutot tester des user dans la rue 

![guerilla_test](http://3.bp.blogspot.com/-zxkwbP2ydjI/TrqAOFTaaEI/AAAAAAAAAoU/prLyM-NzWMI/s1600/Capturer.JPG)
